---
title: "Hengle_Li_HW01"
author: "Hengle Li"
date: "1/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Deviant aggressive behavior (DAB)
## Theory I

Theory I assumes (1) individuals are capable of making rational judgements about outcomes of their future actions based on their past experience; (2) people prefer to gain rewards and avoid punishments. Therefore, deviant aggressive behaviors (DABs) have to be beneficial to the actors, after both the benefits and risks are taken into account. That is, the risks of DABs need to outweigh the benefits for DABs to be reduced. There are two approaches for the government: 

  1. Reduce potential rewards for DABs. For instance, easier access to governmental agencies and better social welfare can discourage individuals from expressing their grievances through crime and violence, now that legal methods offer better rewards. 
    
  2. Increase potential risks for DABs. For instance, increasing penalties for particular offenses, and implementing more effective public security measures may render the costs of DABs too high for them to be profitable.

## Theory II
Theory II assumes (1) hostility appears when individuals experience frustration due to grievances in their lives; (2) figures of authority are potential targets for these individuals to release such hostility upon. If the theory holds true, DABs will be spontaneous, which makes it hard and unrealistic to protect all potential victims. Therefore, the government should seek to reduce situations that can cause individuals to resort to DABs in their frustrations. For instance, the government can provide easier accesses to responsible agencies for individuals to address their personal grievances, including family issues, psychological illness, financial difficulties, etc.

## Theory III
Theory III assumes (1) there are conflicts of interests in the society that lead to systematic discriminations of one group against another by social rules; (2) DABs are rational actions by oppressed groups against the discriminating social rules. There are two approaches for the government to reduce DABs if this theory holds true:

  1.	Reduce systematic discriminations against any social groups. To achieve this, the government will need to reexamine the existent laws and policies, identify which groups are discriminated against by them, and modify the laws and policies accordingly to avoid future discriminations. 
    
  2.	Compensate for losses caused by systematic discriminations, if reduction of systematic discriminations is impossible due to structural or practical difficulties. Given that state legislatures require approval of both the house of representatives and the senate, which inevitably involves further interest conflicts, it may be easier to reduce deviant aggressive individuals’ motivations by offering them appropriate compensations that do not require congress approval. 

## Theory IV
Theory IV assumes (1) DABs are learned from subcultures; (2) there are subcultures that encourage DABs. While some deviant subcultures are controversial because of containing violence, sex, etc., in the US, many of these subcultures are protected by the First Amendment. In this circumstance, the government cannot reduce DABs by directly restricting deviant subcultures. Instead, it can:

  1.	Promote subcultures that do not encourage DABs. By encouraging greater cultural diversity on the cultural market, audience of deviant subcultures may be attracted away from deviant subcultures, and thus exposed to non-deviant-aggressive behaviors. 

  2.	Strengthen civil education in schools. Learning DABs from deviant subcultures does not mean the learners will implement them in practice. By strengthening civil education in schools, people can be better educated on how to rationally appreciate the deviant subcultures that they are exposed to, and thus avoid committing DABs unthoughtfully. 

# Waiting until the last minute
  a. A possible explanation is that people procratinate when they are inconfident and concerned with the possibile outcomes of the tasks in question. They are afraid that they may end up with failure and receive negative comments from other people, and therefore chooose to avoid the tasks until the last minute. 
  
  b. A generalized model is that knowledge about the potential outcomes of a task influences an individual's motivation to complete the task. 
  
  c. An alternative model is that knowledge about the difficulty of a task influences an individual's motivation to complete the task. 
  
  d. predictions:
  * Model b assumption: people prefer positive feedbacks about their works to negative ones.
      + When the individual knows that the task is rewarding, or that he/she is likely to receive positive feedbacks from other people, he/she will be encouraged to complete the task in question on time. For instance, students will gladly turn in papers on time if they are told they will get extra credits for doing so.
      + When the individual knows that the task is unrewarding, or that he/she is likely to receive negative feedbacks from other people, he/she will be afraid of the possible outcomes, and therefore try putting off the task till the last minute. For instance, professors grade exams in the last minute because they know some students will be unhappy about their scores and that there may be negative comments about them because of the scores.
    
  * Model c assumption: people prefer easy tasks to difficult ones.
      + When the task is known to be easy, an individual will be confident and encouraged to complete it in time. Students will be more motivated to complete their assignment if it only asks them to count the houses in the neighborhood, than if it asks them to knock on the door of every house in the neighborhood and interview the residents.
      + When the task is known to be difficult, the individual will be inconfident and discouraged to complete it in time, and therefore put off the task until the last minute. A college student will turn in his/her assignment that asks "1+1=?" in time, but procrastinate on his/her multivariable calculus assignment until the last minute. 
      
# Selecting and fitting a model
1. 
    a. A flexible method is better. When the sample size n is extremely large, a flexible method is unlikely to overfit thanks to sufficient data. On the other hand, an inflexible method won't be able to reduce biases in the data while a flexible method can.
    b. An inflexible method is better. Given a large number of predictors and a small number of observations, a flexible method is likely to be overfitting the observations, which makes it useless in making predictions. 
    c. A flexible method is better. An inflexible method is usually linear, and therefore not good at fitting the highly non-linear model.
    d. An inflexible method is better. A large variance indicates a lot of noises. A flexible method will capture too many noises in the data, and fail in making accurate predictions.
    
2. 
    * bias comes from the model being oversimplified, which is more common among inflexible models. As the model becomes more complicated, i.e. more flexible, bias can be reduced by the model better fitting to the data.
    * variance comes from the model being overcomplex, which is more common among flexible models. It's defined as teh mean squared deviation of predictions of the model from the predictions' expected values over different modeling of the training data. As the model becomes more complex, the mean squared deviation will increase, because its predictions deviate more from those of inflexible models.
    * training error comes from the model being oversimplied and thus failing to capture the training data. As the model becomes more complex, training error will be reduced by its improved performance. 
    * test error comes from the model being either oversimplified or overcomplex. When oversimplified, the model won't be able to fit to the test data, resulting in underfitting. When overcomplex, the model will fit the training data too well to fit other data sets, and result in overfitting. Only when the model is complex to a proper degree can its test error be reduced to the smallest value.
    * irreducible error is irrelevant of the modeling process and inherent in the problem itself. It will not be influenced by the model being changed, and therefore remain a horizontal line as model complexity changes. 